### ISSUE TITLE
Quick-start development setup with Docker

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon-docker#16]
As a developer I'd like an even quicker way to start developing for Avalon with Docker. Currently the Docker instruction on our Github wiki still requires quite a bit of setting up.

### Tasks
- [x] Create docker-compose-dev.yml
- [x] Make necessary changes to accommodate running Avalon in development mode
- [x] Try it in Windows (may not work)
- [ ] Have devs test this setup

**Comment by phuongdh** [comment]
Windows specific:
- Install Git in Windows: line ending should be Linux
- Install Docker: share C drive

TODOs: 
- Advise user to create authentication.yml, controlled_vocab.yml after cloning avalon
- Remove rails server pid file everytime container is brought up
Observations:
- In Windows containers keep dying when taxed with ingesting
